# SPDX-FileCopyrightText: 2025 Kalle Fagerberg
#
# SPDX-License-Identifier: CC0-1.0

version: 3

vars:
  MOON_MODULES:
    sh: echo ./src && find ./example -maxdepth 1 -mindepth 1 -type d
  EXAMPLES:
    sh: find ./example -maxdepth 1 -mindepth 1 -type d

tasks:
  release:
    desc: build and publish release
    cmds:
      - test {{.CLI_ARGS}}
      - grep -F '"{{.CLI_ARGS}}"' moon.mod.json
      - moon publish
      - git tag {{.CLI_ARGS}}
      - git push
      - git push --tags
      - gh release create --generate-notes {{.CLI_ARGS}}

  format:
    cmds:
      - for: { var: MOON_MODULES }
        cmd: moon fmt -C {{.ITEM}}

  lint:
    cmds:
      - for: { var: MOON_MODULES }
        cmd: moon check -C {{.ITEM}}
      - for: { var: MOON_MODULES }
        cmd: moon fmt -C {{.ITEM}} --check

  test:
    deps: [task:moonbit, task:firefly]

  test:moonbit:
    cmds:
      - for: { var: MOON_MODULES }
        cmd: moon test -C {{.ITEM}}

  test:firefly:
    cmds:
      - for: { var: EXAMPLES }
        cmd: firefly_cli build {{.ITEM}}

  all:
    cmds:
      - task: format
      - task: lint
      - task: test
