# SPDX-FileCopyrightText: 2025 Kalle Fagerberg
#
# SPDX-License-Identifier: CC0-1.0

version: 3

vars:
  MOON_MODULES:
    sh: echo ./src && find ./example -maxdepth 1 -mindepth 1 -type d
  EXAMPLES:
    sh: find ./example -maxdepth 1 -mindepth 1 -type d

tasks:
  release:
    desc: build and publish release
    cmds:
      - test {{.CLI_ARGS}}
      - grep -F '"{{.CLI_ARGS}}"' moon.mod.json
      - moon publish
      - git tag {{.CLI_ARGS}}
      - git push
      - git push --tags
      - gh release create --generate-notes {{.CLI_ARGS}}

  format:
    cmds:
      - for: { var: MOON_MODULES }
        cmd: cd {{.ITEM}} && moon fmt

  lint:
    cmds:
      - for: { var: MOON_MODULES }
        cmd: cd {{.ITEM}} && moon check
      - for: { var: MOON_MODULES }
        cmd: cd {{.ITEM}} && moon fmt --check

  test:
    cmds:
      - task: test:moonbit
      - task: test:firefly

  test:moonbit:
    cmds:
      - for: { var: MOON_MODULES }
        cmd: cd {{.ITEM}} && moon test

  test:firefly:
    cmds:
      - for: { var: EXAMPLES }
        cmd: ff build --no-tip {{.ITEM}}

  all:
    cmds:
      - task: format
      - task: lint
      - task: test
